modLoader="javafml" #mandatory
loaderVersion="${loaderVersionRange}" #mandatory

license="${modLicense}"
issueTrackerURL="https://github.com/PickleFace5/Interstellar/issues" #optional

[[mods]] #mandatory
modId="${modId}" #mandatory
version="${modVersion}" #mandatory

displayName="${modName}" #mandatory
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="examplemod.png" #optional
credits=""
authors="${modAuthors}" #optional
description='''${modDescription}'''

#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

#[[mixins]]
#config="${modId}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${modId}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neoVersionRange}" #mandatory
    ordering="BEFORE"
    side="CLIENT"

[[dependencies.${modId}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraftVersionRange}"
    ordering="BEFORE"
    side="CLIENT"

#[features.${modId}]
#openGLVersion="[3.2,)"
